[package]
name = "c_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
antlr-rust = "0.3.0-beta"
petgraph = "0.6.4"
clap = { version = "4.4.6", features = ["derive"] }
